#import "MosqueFeature.h"
#import <MapKit/MapKit.h>
#import <CoreLocation/CoreLocation.h>
#import <UserNotifications/UserNotifications.h>

@interface SalahMosqueController () <CLLocationManagerDelegate,MKMapViewDelegate,NSTableViewDataSource,NSTableViewDelegate,NSWindowDelegate>
@property NSPanel *panel; @property MKMapView *mapView; @property NSTableView *tableView;
@property NSTextField *heading; @property NSTextField *statusLabel; @property NSTextField *privacyLabel;
@property NSButton *searchButton; @property NSButton *directionsButton; @property NSButton *notificationSwitch;
@property CLLocationManager *locationManager; @property CLLocation *currentLocation; @property NSArray<NSDictionary *> *places;
@end

@implementation SalahMosqueController
- (instancetype)init { if ((self=[super init])) { _language=@"en"; _places=@[]; } return self; }
- (NSString *)t:(NSString *)en zh:(NSString *)zh ar:(NSString *)ar ur:(NSString *)ur { return [_language isEqualToString:@"zh"]?zh:([_language isEqualToString:@"ar"]?ar:([_language isEqualToString:@"ur"]?ur:en)); }
- (NSTextField *)label:(NSRect)frame size:(CGFloat)size weight:(NSFontWeight)weight color:(NSColor *)color { NSTextField *v=[[NSTextField alloc] initWithFrame:frame]; v.editable=NO; v.selectable=NO; v.bezeled=NO; v.drawsBackground=NO; v.font=[NSFont systemFontOfSize:size weight:weight]; v.textColor=color; v.lineBreakMode=NSLineBreakByWordWrapping; return v; }
- (NSButton *)button:(NSRect)frame action:(SEL)action { NSButton *b=[[NSButton alloc] initWithFrame:frame]; b.bezelStyle=NSBezelStyleRounded; b.font=[NSFont systemFontOfSize:13 weight:NSFontWeightSemibold]; b.target=self; b.action=action; return b; }

- (void)buildPanel {
  if (_panel) return; _panel=[[NSPanel alloc] initWithContentRect:NSMakeRect(180,100,820,590) styleMask:(NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSWindowStyleMaskResizable|NSWindowStyleMaskUtilityWindow) backing:NSBackingStoreBuffered defer:NO]; _panel.minSize=NSMakeSize(760,540); _panel.floatingPanel=YES; _panel.hidesOnDeactivate=NO; _panel.delegate=self; _panel.collectionBehavior=NSWindowCollectionBehaviorCanJoinAllSpaces|NSWindowCollectionBehaviorFullScreenAuxiliary; NSView *c=_panel.contentView;
  NSColor *ink=[NSColor colorWithCalibratedRed:.20 green:.25 blue:.43 alpha:1],*muted=[NSColor colorWithCalibratedRed:.38 green:.43 blue:.59 alpha:1];
  _heading=[self label:NSMakeRect(24,548,500,28) size:21 weight:NSFontWeightBold color:ink]; [c addSubview:_heading]; _statusLabel=[self label:NSMakeRect(24,518,520,22) size:12 weight:NSFontWeightRegular color:muted]; [c addSubview:_statusLabel];
  _notificationSwitch=[self button:NSMakeRect(566,531,230,28) action:@selector(toggleNotifications:)]; _notificationSwitch.buttonType=NSButtonTypeSwitch; [c addSubview:_notificationSwitch];
  _mapView=[[MKMapView alloc] initWithFrame:NSMakeRect(24,92,520,416)]; _mapView.delegate=self; _mapView.showsZoomControls=YES; _mapView.showsUserLocation=YES; _mapView.autoresizingMask=NSViewWidthSizable|NSViewHeightSizable; [c addSubview:_mapView];
  NSScrollView *scroll=[[NSScrollView alloc] initWithFrame:NSMakeRect(560,172,236,336)]; scroll.hasVerticalScroller=YES; scroll.borderType=NSBezelBorder; scroll.autoresizingMask=NSViewMinXMargin|NSViewHeightSizable; _tableView=[[NSTableView alloc] initWithFrame:scroll.contentView.bounds]; _tableView.headerView=nil; _tableView.rowHeight=62; _tableView.delegate=self; _tableView.dataSource=self; _tableView.doubleAction=@selector(openDirections:); _tableView.target=self; NSTableColumn *col=[[NSTableColumn alloc] initWithIdentifier:@"mosque"]; col.width=228; [_tableView addTableColumn:col]; scroll.documentView=_tableView; [c addSubview:scroll];
  _privacyLabel=[self label:NSMakeRect(560,92,236,68) size:11 weight:NSFontWeightRegular color:muted]; _privacyLabel.maximumNumberOfLines=4; [c addSubview:_privacyLabel];
  _searchButton=[self button:NSMakeRect(24,36,346,36) action:@selector(findNearby:)]; _searchButton.keyEquivalent=@"\r"; [c addSubview:_searchButton]; _directionsButton=[self button:NSMakeRect(560,36,236,36) action:@selector(openDirections:)]; _directionsButton.enabled=NO; [c addSubview:_directionsButton];
}
- (void)refreshLabels {
  _panel.title=[self t:@"Nearby Mosques" zh:@"附近清真寺" ar:@"المساجد القريبة" ur:@"Qareebi Masajid"]; _heading.stringValue=[self t:@"Find a peaceful place nearby" zh:@"寻找离你最近的清真寺" ar:@"اعثر على مسجد قريب" ur:@"Qareeb masjid talaash karein"];
  if (!_statusLabel.stringValue.length) _statusLabel.stringValue=[self t:@"Location is requested only when you use this feature." zh:@"仅在你使用此功能时请求当前位置。" ar:@"يُطلب موقعك فقط عند استخدام هذه الميزة." ur:@"Location sirf is feature ke istemal par li jati hai."];
  _searchButton.title=[self t:@"Find nearby mosques" zh:@"查找附近清真寺" ar:@"البحث عن المساجد القريبة" ur:@"Qareebi masajid dhoondein"]; _directionsButton.title=[self t:@"Open selected route" zh:@"打开所选路线" ar:@"فتح مسار المسجد المحدد" ur:@"Chuna hua rasta kholein"];
  _notificationSwitch.title=[self t:@"Mosque suggestions before prayer" zh:@"礼拜前推荐附近清真寺" ar:@"اقتراح مسجد قبل الصلاة" ur:@"Namaz se pehle masjid reminder"]; _notificationSwitch.state=[NSUserDefaults.standardUserDefaults boolForKey:@"salahMosqueNotifications"]?NSControlStateValueOn:NSControlStateValueOff;
  _privacyLabel.stringValue=[self t:@"Privacy: search uses Apple MapKit. Precise location is not stored. Results may be incomplete; verify locally." zh:@"隐私：搜索使用 Apple MapKit，不保存精确位置。结果可能不完整，请结合当地信息确认。" ar:@"الخصوصية: يستخدم البحث Apple MapKit ولا نحفظ الموقع الدقيق. قد تكون النتائج غير مكتملة." ur:@"Privacy: search Apple MapKit se hoti hai; exact location save nahi hoti. Results mukammal na bhi hon."];
}
- (void)show { [self buildPanel]; [self refreshLabels]; [_panel makeKeyAndOrderFront:nil]; [NSApp activateIgnoringOtherApps:YES]; }

- (void)findNearby:(id)sender { [self requestLocation]; }
- (void)requestLocation { if (!_locationManager) { _locationManager=[CLLocationManager new]; _locationManager.delegate=self; _locationManager.desiredAccuracy=kCLLocationAccuracyHundredMeters; } CLAuthorizationStatus s=_locationManager.authorizationStatus; if (s==kCLAuthorizationStatusNotDetermined) [_locationManager requestWhenInUseAuthorization]; else if (s==kCLAuthorizationStatusDenied||s==kCLAuthorizationStatusRestricted) _statusLabel.stringValue=[self t:@"Location access is off. Enable it in System Settings › Privacy & Security › Location Services." zh:@"定位权限已关闭。请前往“系统设置 › 隐私与安全性 › 定位服务”开启。" ar:@"خدمة الموقع متوقفة. فعّلها من إعدادات النظام والخصوصية والأمان." ur:@"Location access band hai. System Settings › Privacy & Security mein enable karein."]; else { _statusLabel.stringValue=[self t:@"Finding your location…" zh:@"正在获取你的位置…" ar:@"جارٍ تحديد موقعك…" ur:@"Aap ki location mil rahi hai…"]; [_locationManager requestLocation]; } }
- (void)locationManagerDidChangeAuthorization:(CLLocationManager *)m { if (m.authorizationStatus==kCLAuthorizationStatusAuthorized||m.authorizationStatus==kCLAuthorizationStatusAuthorizedAlways) [m requestLocation]; }
- (void)locationManager:(CLLocationManager *)m didFailWithError:(NSError *)error { dispatch_async(dispatch_get_main_queue(),^{ self.statusLabel.stringValue=[self t:@"I couldn’t get your location. Check Location Services and try again." zh:@"暂时无法获取位置，请检查定位服务后重试。" ar:@"تعذر تحديد موقعك. تحقق من خدمة الموقع وحاول مجددًا." ur:@"Location nahi mil saki. Location Services check karke dobara koshish karein."]; }); }
- (void)locationManager:(CLLocationManager *)m didUpdateLocations:(NSArray<CLLocation *> *)locations { CLLocation *l=locations.lastObject; if (!l||fabs([l.timestamp timeIntervalSinceNow])>120) return; _currentLocation=l; [self searchMapKit:l]; }

- (void)searchMapKit:(CLLocation *)location {
  _searchButton.enabled=NO; _statusLabel.stringValue=[self t:@"Searching Apple Maps for nearby mosques…" zh:@"正在通过 Apple 地图搜索附近清真寺…" ar:@"جارٍ البحث عن المساجد القريبة عبر خرائط Apple…" ur:@"Apple Maps par qareebi masajid dhoondi ja rahi hain…"];
  MKLocalSearchRequest *request=[MKLocalSearchRequest new]; request.naturalLanguageQuery=@"mosque"; request.region=MKCoordinateRegionMakeWithDistance(location.coordinate,20000,20000); MKLocalSearch *search=[[MKLocalSearch alloc] initWithRequest:request];
  [search startWithCompletionHandler:^(MKLocalSearchResponse *response,NSError *error){ dispatch_async(dispatch_get_main_queue(),^{ self.searchButton.enabled=YES; if (error) { self.statusLabel.stringValue=[self t:@"Apple Maps search failed. Check the network and try again." zh:@"Apple 地图搜索失败，请检查网络后重试。" ar:@"فشل البحث في خرائط Apple. تحقق من الشبكة وحاول مجددًا." ur:@"Apple Maps search fail hui. Network check karke dobara koshish karein."]; return; } NSMutableArray *clean=[NSMutableArray new]; for (MKMapItem *item in response.mapItems) { CLLocationCoordinate2D coordinate=item.placemark.coordinate; CLLocation *target=[[CLLocation alloc] initWithLatitude:coordinate.latitude longitude:coordinate.longitude]; double distance=[location distanceFromLocation:target]; if (distance>10000) continue; NSString *name=item.name.length?item.name:[self t:@"Mosque" zh:@"清真寺" ar:@"مسجد" ur:@"Masjid"]; NSString *address=item.placemark.title ?: @""; [clean addObject:@{@"name":name,@"address":address,@"lat":@(coordinate.latitude),@"lon":@(coordinate.longitude),@"distance":@(distance)}]; } [clean sortUsingComparator:^NSComparisonResult(NSDictionary *a,NSDictionary *b){ return [a[@"distance"] compare:b[@"distance"]]; }]; if (clean.count>10) [clean removeObjectsInRange:NSMakeRange(10,clean.count-10)]; self.places=clean; [self displayPlaces]; if (self.places.count&&[NSUserDefaults.standardUserDefaults boolForKey:@"salahMosqueNotifications"]) [self schedule:self.places.firstObject]; }); }];
}

- (void)displayPlaces { [_mapView removeAnnotations:_mapView.annotations]; [_mapView setRegion:MKCoordinateRegionMakeWithDistance(_currentLocation.coordinate,7000,7000) animated:YES]; for (NSDictionary *p in _places) { MKPointAnnotation *pin=[MKPointAnnotation new]; pin.coordinate=CLLocationCoordinate2DMake([p[@"lat"] doubleValue],[p[@"lon"] doubleValue]); pin.title=p[@"name"]; pin.subtitle=p[@"address"]; [_mapView addAnnotation:pin]; } [_tableView reloadData]; if (_places.count) { [_tableView selectRowIndexes:[NSIndexSet indexSetWithIndex:0] byExtendingSelection:NO]; _directionsButton.enabled=YES; _statusLabel.stringValue=[NSString stringWithFormat:[self t:@"Found %lu nearby mosques, ordered by straight-line distance." zh:@"找到 %lu 座附近清真寺，已按直线距离排序。" ar:@"تم العثور على %lu مسجدًا قريبًا، مرتبة حسب المسافة المباشرة." ur:@"%lu qareebi masajid mil gayi hain, seedhe fasle ke hisaab se."],(unsigned long)_places.count]; } else { _directionsButton.enabled=NO; _statusLabel.stringValue=[self t:@"No mosque was found within 10 km. Try again from another location." zh:@"10 公里范围内未找到清真寺，可换一个位置后重试。" ar:@"لم يُعثر على مسجد ضمن 10 كم. حاول من موقع آخر." ur:@"10 km ke andar masjid nahi mili. Doosri location se koshish karein."]; } }
- (NSInteger)numberOfRowsInTableView:(NSTableView *)tv { return _places.count; }
- (NSView *)tableView:(NSTableView *)tv viewForTableColumn:(NSTableColumn *)column row:(NSInteger)row { NSTableCellView *cell=[tv makeViewWithIdentifier:@"MosqueCell" owner:self]; if (!cell) { cell=[[NSTableCellView alloc] initWithFrame:NSMakeRect(0,0,230,62)]; cell.identifier=@"MosqueCell"; NSTextField *title=[self label:NSMakeRect(8,34,212,20) size:13 weight:NSFontWeightSemibold color:NSColor.labelColor]; [cell addSubview:title]; NSTextField *detail=[self label:NSMakeRect(8,5,212,30) size:11 weight:NSFontWeightRegular color:NSColor.secondaryLabelColor]; detail.maximumNumberOfLines=2; [cell addSubview:detail]; } NSDictionary *p=_places[row]; NSTextField *title=cell.subviews.count>0?cell.subviews[0]:nil,*detail=cell.subviews.count>1?cell.subviews[1]:nil; title.stringValue=p[@"name"]; double d=[p[@"distance"] doubleValue]; detail.stringValue=[NSString stringWithFormat:@"%@ · %@",d<1000?[NSString stringWithFormat:@"%.0f m",d]:[NSString stringWithFormat:@"%.1f km",d/1000.0],p[@"address"]]; return cell; }
- (void)tableViewSelectionDidChange:(NSNotification *)n { _directionsButton.enabled=_tableView.selectedRow>=0; }
- (void)openDirections:(id)sender { NSInteger row=_tableView.selectedRow; if (row<0||row>=_places.count) return; NSDictionary *p=_places[row]; MKMapItem *item=[[MKMapItem alloc] initWithPlacemark:[[MKPlacemark alloc] initWithCoordinate:CLLocationCoordinate2DMake([p[@"lat"] doubleValue],[p[@"lon"] doubleValue])]]; item.name=p[@"name"]; [MKMapItem openMapsWithItems:@[item] launchOptions:@{MKLaunchOptionsDirectionsModeKey:MKLaunchOptionsDirectionsModeDriving}]; }

- (void)toggleNotifications:(NSButton *)sender { BOOL on=sender.state==NSControlStateValueOn; [NSUserDefaults.standardUserDefaults setBool:on forKey:@"salahMosqueNotifications"]; if (!on) { [UNUserNotificationCenter.currentNotificationCenter removePendingNotificationRequestsWithIdentifiers:@[@"salahcat-nearest-mosque"]]; _statusLabel.stringValue=[self t:@"Nearby mosque suggestions are off." zh:@"附近清真寺提醒已关闭。" ar:@"تم إيقاف اقتراحات المساجد القريبة." ur:@"Qareebi masjid reminders band hain."]; return; } [UNUserNotificationCenter.currentNotificationCenter requestAuthorizationWithOptions:(UNAuthorizationOptionAlert|UNAuthorizationOptionSound) completionHandler:^(BOOL granted,NSError *error){ dispatch_async(dispatch_get_main_queue(),^{ if (!granted) { sender.state=NSControlStateValueOff; [NSUserDefaults.standardUserDefaults setBool:NO forKey:@"salahMosqueNotifications"]; self.statusLabel.stringValue=[self t:@"Notifications are blocked in System Settings." zh:@"系统设置中未允许通知，请开启后重试。" ar:@"الإشعارات محظورة في إعدادات النظام." ur:@"Notifications System Settings mein blocked hain."]; } else if (self.places.count) [self schedule:self.places.firstObject]; else [self findNearby:nil]; }); }]; }
- (void)schedule:(NSDictionary *)place { NSDate *now=NSDate.date,*next=nil; NSString *nextName=nil; NSDateFormatter *f=[NSDateFormatter new]; f.locale=[[NSLocale alloc] initWithLocaleIdentifier:@"en_US_POSIX"]; f.timeZone=NSTimeZone.localTimeZone; f.dateFormat=@"yyyy-MM-dd HH:mm"; NSDateFormatter *day=[NSDateFormatter new]; day.locale=f.locale; day.timeZone=f.timeZone; day.dateFormat=@"yyyy-MM-dd"; NSString *today=[day stringFromDate:now]; for (NSString *name in @[@"Fajr",@"Dhuhr",@"Asr",@"Maghrib",@"Isha"]) { NSString *time=_prayerTimings[name]; if (time.length<5) continue; NSDate *candidate=[f dateFromString:[NSString stringWithFormat:@"%@ %@",today,[time substringToIndex:5]]]; if ([candidate compare:now]==NSOrderedDescending&&(!next||[candidate compare:next]==NSOrderedAscending)) { next=candidate; nextName=name; } } if (!next) return; NSDate *fire=[next dateByAddingTimeInterval:-1800]; if ([fire compare:now]!=NSOrderedDescending) fire=[now dateByAddingTimeInterval:5]; double d=[place[@"distance"] doubleValue]; NSString *distance=d<1000?[NSString stringWithFormat:@"%.0f m",d]:[NSString stringWithFormat:@"%.1f km",d/1000.0]; UNMutableNotificationContent *c=[UNMutableNotificationContent new]; c.title=[self t:@"Nearby mosque · Prayer Cat" zh:@"附近清真寺 · 礼拜喵" ar:@"مسجد قريب · Salah Cat" ur:@"Qareebi Masjid · Namaz Cat"]; c.body=[NSString stringWithFormat:[self t:@"%@ is next. %@ is about %@ away." zh:@"下一次是 %@。%@ 距你约 %@。" ar:@"الصلاة القادمة هي %@. يبعد %@ حوالي %@." ur:@"Agli namaz %@ hai. %@ taqreeban %@ door hai."],nextName,place[@"name"],distance]; c.sound=UNNotificationSound.defaultSound; NSDateComponents *dc=[NSCalendar.currentCalendar components:(NSCalendarUnitYear|NSCalendarUnitMonth|NSCalendarUnitDay|NSCalendarUnitHour|NSCalendarUnitMinute) fromDate:fire]; UNNotificationRequest *r=[UNNotificationRequest requestWithIdentifier:@"salahcat-nearest-mosque" content:c trigger:[UNCalendarNotificationTrigger triggerWithDateMatchingComponents:dc repeats:NO]]; [UNUserNotificationCenter.currentNotificationCenter addNotificationRequest:r withCompletionHandler:nil]; }
- (void)refreshForReminderIfNeeded { if (![NSUserDefaults.standardUserDefaults boolForKey:@"salahMosqueNotifications"]) return; NSDate *last=[NSUserDefaults.standardUserDefaults objectForKey:@"salahMosqueLastRefresh"]; if (last&&[NSDate.date timeIntervalSinceDate:last]<21600) return; [NSUserDefaults.standardUserDefaults setObject:NSDate.date forKey:@"salahMosqueLastRefresh"]; [self requestLocation]; }
@end
